# Generated by Django 4.1.1 on 2022-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateField(null=True),
        ),
    ]
